languageCode = "zh-cn"
metaDataFormat = "yaml"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "https://zhu327.github.io/"
canonifyurls = true
pygmentsuseclasses = true
PygmentsCodeFences = true
paginate = 5.0

[permalinks]
post = ":year/:month/:day/:title/"
fixed = ":title/"

[taxonomies]
tag = "tags"

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]
Title = "跬步"
Tagline = "On Coding"
Author = "Timmy"
DateForm = "Jan 2 2006"
Github = "https://github.com/zhu327"

[params.utteranc]
  enable = true
  repo = "zhu327/zhu327.github.io"
  issueTerm = "og:title"
  theme = "github-light"
